// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element

import 'package:attendance_management/models/attendance_audit.dart' as p51;
import 'package:attendance_management/models/attendance_log.dart' as p52;
import 'package:attendance_management/models/attendance_register.dart' as p49;
import 'package:attendance_management/models/attendee.dart' as p53;
import 'package:attendance_management/models/staff.dart' as p50;

import 'data_model.dart' as p0;
import 'entities/additional_fields_type.dart' as p1;
import 'entities/address.dart' as p2;
import 'entities/address_type.dart' as p3;
import 'entities/attributes.dart' as p4;
import 'entities/beneficiary_type.dart' as p5;
import 'entities/blood_group.dart' as p6;
import 'entities/boundary.dart' as p7;
import 'entities/deliver_strategy_type.dart' as p8;
import 'entities/document.dart' as p9;
import 'entities/downsync.dart' as p10;
import 'entities/facility.dart' as p11;
import 'entities/gender.dart' as p12;
import 'entities/h_f_referral.dart' as p13;
import 'entities/household.dart' as p14;
import 'entities/household_member.dart' as p15;
import 'entities/identifier.dart' as p16;
import 'entities/identifier_types.dart' as p17;
import 'entities/individual.dart' as p18;
import 'entities/locality.dart' as p19;
import 'entities/name.dart' as p20;
import 'entities/product.dart' as p21;
import 'entities/product_variant.dart' as p22;
import 'entities/project.dart' as p23;
import 'entities/project_beneficiary.dart' as p24;
import 'entities/project_facility.dart' as p25;
import 'entities/project_product_variant.dart' as p26;
import 'entities/project_resource.dart' as p27;
import 'entities/project_staff.dart' as p28;
import 'entities/project_type.dart' as p29;
import 'entities/referral.dart' as p30;
import 'entities/roles_type.dart' as p31;
import 'entities/service.dart' as p32;
import 'entities/service_attributes.dart' as p33;
import 'entities/service_definition.dart' as p34;
import 'entities/side_effect.dart' as p35;
import 'entities/status.dart' as p36;
import 'entities/stock.dart' as p37;
import 'entities/stock_reconciliation.dart' as p38;
import 'entities/target.dart' as p39;
import 'entities/task.dart' as p40;
import 'entities/task_resource.dart' as p41;
import 'entities/transaction_reason.dart' as p42;
import 'entities/transaction_type.dart' as p43;
import 'entities/user.dart' as p44;
import 'oplog/oplog_entry.dart' as p45;
import 'pgr_complaints/pgr_address.dart' as p46;
import 'pgr_complaints/pgr_complaints.dart' as p47;
import 'pgr_complaints/pgr_complaints_response.dart' as p48;

void initializeMappers() {
  p0.EntityModelMapper.ensureInitialized();
  p0.EntitySearchModelMapper.ensureInitialized();
  p0.AdditionalFieldsMapper.ensureInitialized();
  p0.AdditionalFieldMapper.ensureInitialized();
  p0.ClientAuditDetailsMapper.ensureInitialized();
  p0.AuditDetailsMapper.ensureInitialized();
  p1.AdditionalFieldsTypeMapper.ensureInitialized();
  p2.AddressSearchModelMapper.ensureInitialized();
  p2.AddressModelMapper.ensureInitialized();
  p2.AddressAdditionalFieldsMapper.ensureInitialized();
  p3.AddressTypeMapper.ensureInitialized();
  p4.AttributesSearchModelMapper.ensureInitialized();
  p4.AttributesModelMapper.ensureInitialized();
  p4.AttributesAdditionalFieldsMapper.ensureInitialized();
  p5.BeneficiaryTypeMapper.ensureInitialized();
  p6.BloodGroupMapper.ensureInitialized();
  p7.BoundarySearchModelMapper.ensureInitialized();
  p7.BoundaryModelMapper.ensureInitialized();
  p8.DeliverStrategyTypeMapper.ensureInitialized();
  p9.DocumentSearchModelMapper.ensureInitialized();
  p9.DocumentModelMapper.ensureInitialized();
  p9.DocumentAdditionalFieldsMapper.ensureInitialized();
  p10.DownsyncSearchModelMapper.ensureInitialized();
  p10.DownsyncModelMapper.ensureInitialized();
  p10.DownsyncAdditionalFieldsMapper.ensureInitialized();
  p11.FacilitySearchModelMapper.ensureInitialized();
  p11.FacilityModelMapper.ensureInitialized();
  p11.FacilityAdditionalFieldsMapper.ensureInitialized();
  p12.GenderMapper.ensureInitialized();
  p13.HFReferralSearchModelMapper.ensureInitialized();
  p13.HFReferralModelMapper.ensureInitialized();
  p13.HFReferralAdditionalFieldsMapper.ensureInitialized();
  p14.HouseholdSearchModelMapper.ensureInitialized();
  p14.HouseholdModelMapper.ensureInitialized();
  p14.HouseholdAdditionalFieldsMapper.ensureInitialized();
  p15.HouseholdMemberSearchModelMapper.ensureInitialized();
  p15.HouseholdMemberModelMapper.ensureInitialized();
  p15.HouseholdMemberAdditionalFieldsMapper.ensureInitialized();
  p16.IdentifierSearchModelMapper.ensureInitialized();
  p16.IdentifierModelMapper.ensureInitialized();
  p16.IdentifierAdditionalFieldsMapper.ensureInitialized();
  p17.IdentifierTypesMapper.ensureInitialized();
  p18.IndividualSearchModelMapper.ensureInitialized();
  p18.IndividualModelMapper.ensureInitialized();
  p18.IndividualAdditionalFieldsMapper.ensureInitialized();
  p19.LocalitySearchModelMapper.ensureInitialized();
  p19.LocalityModelMapper.ensureInitialized();
  p19.LocalityAdditionalFieldsMapper.ensureInitialized();
  p20.NameSearchModelMapper.ensureInitialized();
  p20.NameModelMapper.ensureInitialized();
  p20.NameAdditionalFieldsMapper.ensureInitialized();
  p21.ProductSearchModelMapper.ensureInitialized();
  p21.ProductModelMapper.ensureInitialized();
  p21.ProductAdditionalFieldsMapper.ensureInitialized();
  p22.ProductVariantSearchModelMapper.ensureInitialized();
  p22.ProductVariantModelMapper.ensureInitialized();
  p22.ProductVariantAdditionalFieldsMapper.ensureInitialized();
  p23.ProjectSearchModelMapper.ensureInitialized();
  p23.ProjectModelMapper.ensureInitialized();
  p23.ProjectAdditionalFieldsMapper.ensureInitialized();
  p24.ProjectBeneficiarySearchModelMapper.ensureInitialized();
  p24.ProjectBeneficiaryModelMapper.ensureInitialized();
  p24.ProjectBeneficiaryAdditionalFieldsMapper.ensureInitialized();
  p25.ProjectFacilitySearchModelMapper.ensureInitialized();
  p25.ProjectFacilityModelMapper.ensureInitialized();
  p25.ProjectFacilityAdditionalFieldsMapper.ensureInitialized();
  p26.ProjectProductVariantSearchModelMapper.ensureInitialized();
  p26.ProjectProductVariantModelMapper.ensureInitialized();
  p26.ProjectProductVariantAdditionalFieldsMapper.ensureInitialized();
  p27.ProjectResourceSearchModelMapper.ensureInitialized();
  p27.ProjectResourceModelMapper.ensureInitialized();
  p27.ProjectResourceAdditionalFieldsMapper.ensureInitialized();
  p28.ProjectStaffSearchModelMapper.ensureInitialized();
  p28.ProjectStaffModelMapper.ensureInitialized();
  p28.ProjectStaffAdditionalFieldsMapper.ensureInitialized();
  p29.ProjectTypeSearchModelMapper.ensureInitialized();
  p29.ProjectTypeModelMapper.ensureInitialized();
  p29.ProjectTypeAdditionalFieldsMapper.ensureInitialized();
  p30.ReferralSearchModelMapper.ensureInitialized();
  p30.ReferralModelMapper.ensureInitialized();
  p30.ReferralAdditionalFieldsMapper.ensureInitialized();
  p31.RolesTypeMapper.ensureInitialized();
  p32.ServiceSearchModelMapper.ensureInitialized();
  p32.ServiceModelMapper.ensureInitialized();
  p32.ServiceAdditionalFieldsMapper.ensureInitialized();
  p33.ServiceAttributesSearchModelMapper.ensureInitialized();
  p33.ServiceAttributesModelMapper.ensureInitialized();
  p33.ServiceAttributesAdditionalFieldsMapper.ensureInitialized();
  p34.ServiceDefinitionSearchModelMapper.ensureInitialized();
  p34.ServiceDefinitionModelMapper.ensureInitialized();
  p34.ServiceDefinitionAdditionalFieldsMapper.ensureInitialized();
  p35.SideEffectSearchModelMapper.ensureInitialized();
  p35.SideEffectModelMapper.ensureInitialized();
  p35.SideEffectAdditionalFieldsMapper.ensureInitialized();
  p36.StatusMapper.ensureInitialized();
  p37.StockSearchModelMapper.ensureInitialized();
  p37.StockModelMapper.ensureInitialized();
  p37.StockAdditionalFieldsMapper.ensureInitialized();
  p38.StockReconciliationSearchModelMapper.ensureInitialized();
  p38.StockReconciliationModelMapper.ensureInitialized();
  p38.StockReconciliationAdditionalFieldsMapper.ensureInitialized();
  p39.TargetSearchModelMapper.ensureInitialized();
  p39.TargetModelMapper.ensureInitialized();
  p39.TargetAdditionalFieldsMapper.ensureInitialized();
  p40.TaskSearchModelMapper.ensureInitialized();
  p40.TaskModelMapper.ensureInitialized();
  p40.TaskAdditionalFieldsMapper.ensureInitialized();
  p41.TaskResourceSearchModelMapper.ensureInitialized();
  p41.TaskResourceModelMapper.ensureInitialized();
  p41.TaskResourceAdditionalFieldsMapper.ensureInitialized();
  p42.TransactionReasonMapper.ensureInitialized();
  p43.TransactionTypeMapper.ensureInitialized();
  p44.UserSearchModelMapper.ensureInitialized();
  p44.UserModelMapper.ensureInitialized();
  p44.UserAdditionalFieldsMapper.ensureInitialized();
  p45.OpLogEntryMapper.ensureInitialized();
  p45.AdditionalIdMapper.ensureInitialized();
  p45.DataOperationMapper.ensureInitialized();
  p45.ApiOperationMapper.ensureInitialized();
  p46.PgrAddressModelMapper.ensureInitialized();
  p46.GeoLocationMapper.ensureInitialized();
  p47.PgrComplaintModelMapper.ensureInitialized();
  p47.PgrComplainantModelMapper.ensureInitialized();
  p47.PgrRolesModelMapper.ensureInitialized();
  p47.PgrServiceSearchModelMapper.ensureInitialized();
  p47.PgrServiceModelMapper.ensureInitialized();
  p47.PgrWorkflowModelMapper.ensureInitialized();
  p47.PgrFiltersMapper.ensureInitialized();
  p47.PgrSearchKeysMapper.ensureInitialized();
  p47.PgrAdditionalDetailsMapper.ensureInitialized();
  p47.PgrServiceApplicationStatusMapper.ensureInitialized();
  p48.PgrServiceCreateResponseModelMapper.ensureInitialized();
  p48.PgrComplaintResponseModelMapper.ensureInitialized();
  p48.PgrComplainantResponseModelMapper.ensureInitialized();
  p48.PgrServiceResponseModelMapper.ensureInitialized();
  p49.AttendanceRegisterModelMapper.ensureInitialized();
  p50.StaffModelMapper.ensureInitialized();
  p51.AttendanceAuditDetailsMapper.ensureInitialized();
  p52.AttendanceLogModelMapper.ensureInitialized();
  p53.AttendeeModelMapper.ensureInitialized();
}
